version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/apps/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/apps/tg-bot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
